package algo.string_and_array;

import java.util.Arrays;

public class FindArrayDiff {
	/*
	 * 
	 * 
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
	 */

	public char findTheDifference(String s, String t) {
		char[] c1 = s.toCharArray();
		char[] c2 = t.toCharArray();

		Arrays.sort(c1);
		Arrays.sort(c2);

		int i=0;
		while(i<c2.length){
			if(i >= c1.length || c1[i] != c2[i] ) return c2[i];
			i++;
		}
		return '0';
	}

	public static void main(String[] args){
		FindArrayDiff test = new FindArrayDiff();

		System.out.println(test.findTheDifference("abcd", "ambcd"));
	}
}
